services:
  db:
    image: postgres:16
    container_name: logsummary-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-appuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-apppass}
      POSTGRES_DB: ${DB_NAME:-logsummary}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-appuser} -d ${DB_NAME:-logsummary}"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  pgdata:
